// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamControlV2.Infrastructure;

namespace TeamControlV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220114113846_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamControlV2.Domain.Models.ADMIN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("Id");

                    b.ToTable("ADMIN");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.BONUS_AND_PRIZE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE");

                    b.Property<int?>("EMP_ID")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID1");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID");

                    b.Property<bool>("IsPrize")
                        .HasColumnType("bit")
                        .HasColumnName("IS_PRIZE");

                    b.Property<int?>("PROJECT_ID")
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID1");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REASON");

                    b.HasKey("Id");

                    b.HasIndex("EMP_ID");

                    b.HasIndex("PROJECT_ID");

                    b.ToTable("BONUS_AND_PRIZE");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.CUSTOMER", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("POSITION");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SURNAME");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("CUSTOMER");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.CUSTOMER_TO_PROJECT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CUSTOMER_ID")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID1");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("IS_MAIN");

                    b.Property<int?>("PROJECT_ID")
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID1");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID");

                    b.HasKey("Id");

                    b.HasIndex("CUSTOMER_ID");

                    b.HasIndex("PROJECT_ID");

                    b.ToTable("CUSTOMER_TO_PROJECT");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.EMPLOYEE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BIOGRAPHY");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<DateTime>("RecruitmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("RECRUITMENT_DATE");

                    b.Property<string>("RelativesPhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RELATIVES_PHONE_NUMBER");

                    b.Property<double>("Salary")
                        .HasColumnType("float")
                        .HasColumnName("SALARY");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("STATUS");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SURNAME");

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEE");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.EMPLOYEE_TO_POSITION", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EMP_ID")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID1");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID");

                    b.Property<int?>("POS_ID")
                        .HasColumnType("int")
                        .HasColumnName("POS_ID1");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("POS_ID");

                    b.HasKey("Id");

                    b.HasIndex("EMP_ID");

                    b.HasIndex("POS_ID");

                    b.ToTable("EMPLOYEE_TO_POSITION");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.POSITION", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KEY");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("POSITION");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.PROJECT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<int?>("STATUS_ID")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_ID1");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_ID");

                    b.Property<int?>("TEAM_LEADER_ID")
                        .HasColumnType("int")
                        .HasColumnName("TEAM_LEADER_ID1");

                    b.Property<int>("TeamLeaderId")
                        .HasColumnType("int")
                        .HasColumnName("TEAM_LEADER_ID");

                    b.HasKey("Id");

                    b.HasIndex("STATUS_ID");

                    b.HasIndex("TEAM_LEADER_ID");

                    b.ToTable("PROJECT");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.PROJECT_STATUS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COLOR");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KEY");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("PROJECT_STATUS");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.PROJECT_TO_EMPLOYEE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EMP_ID")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID1");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("IS_MAIN");

                    b.Property<int?>("POS_ID")
                        .HasColumnType("int")
                        .HasColumnName("POS_ID1");

                    b.Property<int?>("PROJECT_ID")
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID1");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("POS_ID");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("PROJECT_ID");

                    b.HasKey("Id");

                    b.HasIndex("EMP_ID");

                    b.HasIndex("POS_ID");

                    b.HasIndex("PROJECT_ID");

                    b.ToTable("PROJECT_TO_EMPLOYEE");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.SALARY", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("AMOUNT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE");

                    b.Property<int?>("EMP_ID")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID1");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID");

                    b.HasKey("Id");

                    b.HasIndex("EMP_ID");

                    b.ToTable("SALARY");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.VACATION", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE");

                    b.Property<int?>("EMP_ID")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID1");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EMP_ID");

                    b.Property<int>("Period")
                        .HasColumnType("int")
                        .HasColumnName("PERIOD");

                    b.Property<int?>("REASON_ID")
                        .HasColumnType("int")
                        .HasColumnName("REASON_ID1");

                    b.Property<int>("VacationReasonId")
                        .HasColumnType("int")
                        .HasColumnName("REASON_ID");

                    b.HasKey("Id");

                    b.HasIndex("EMP_ID");

                    b.HasIndex("REASON_ID");

                    b.ToTable("VACATION");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.VACATION_REASON", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KEY");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("VACATION_REASON");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.BONUS_AND_PRIZE", b =>
                {
                    b.HasOne("TeamControlV2.Domain.Models.EMPLOYEE", "Employee")
                        .WithMany()
                        .HasForeignKey("EMP_ID");

                    b.HasOne("TeamControlV2.Domain.Models.PROJECT", "Project")
                        .WithMany()
                        .HasForeignKey("PROJECT_ID");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.CUSTOMER_TO_PROJECT", b =>
                {
                    b.HasOne("TeamControlV2.Domain.Models.CUSTOMER", "Customer")
                        .WithMany()
                        .HasForeignKey("CUSTOMER_ID");

                    b.HasOne("TeamControlV2.Domain.Models.PROJECT", "Project")
                        .WithMany()
                        .HasForeignKey("PROJECT_ID");

                    b.Navigation("Customer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.EMPLOYEE_TO_POSITION", b =>
                {
                    b.HasOne("TeamControlV2.Domain.Models.EMPLOYEE", "Employee")
                        .WithMany()
                        .HasForeignKey("EMP_ID");

                    b.HasOne("TeamControlV2.Domain.Models.POSITION", "Position")
                        .WithMany()
                        .HasForeignKey("POS_ID");

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.PROJECT", b =>
                {
                    b.HasOne("TeamControlV2.Domain.Models.PROJECT_STATUS", "Status")
                        .WithMany()
                        .HasForeignKey("STATUS_ID");

                    b.HasOne("TeamControlV2.Domain.Models.EMPLOYEE", "TeamLeader")
                        .WithMany()
                        .HasForeignKey("TEAM_LEADER_ID");

                    b.Navigation("Status");

                    b.Navigation("TeamLeader");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.PROJECT_TO_EMPLOYEE", b =>
                {
                    b.HasOne("TeamControlV2.Domain.Models.EMPLOYEE", "Employee")
                        .WithMany()
                        .HasForeignKey("EMP_ID");

                    b.HasOne("TeamControlV2.Domain.Models.POSITION", "Position")
                        .WithMany()
                        .HasForeignKey("POS_ID");

                    b.HasOne("TeamControlV2.Domain.Models.PROJECT", "Project")
                        .WithMany()
                        .HasForeignKey("PROJECT_ID");

                    b.Navigation("Employee");

                    b.Navigation("Position");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.SALARY", b =>
                {
                    b.HasOne("TeamControlV2.Domain.Models.EMPLOYEE", "Employee")
                        .WithMany()
                        .HasForeignKey("EMP_ID");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TeamControlV2.Domain.Models.VACATION", b =>
                {
                    b.HasOne("TeamControlV2.Domain.Models.EMPLOYEE", "Employee")
                        .WithMany()
                        .HasForeignKey("EMP_ID");

                    b.HasOne("TeamControlV2.Domain.Models.VACATION_REASON", "VacationReason")
                        .WithMany()
                        .HasForeignKey("REASON_ID");

                    b.Navigation("Employee");

                    b.Navigation("VacationReason");
                });
#pragma warning restore 612, 618
        }
    }
}
